### ISSUE TITLE
closing app

### ISSUE THREAD

**Issue by midhunpmohan** [ahmeturun/Camera-Test#1]
app crashing immediately while trying to launch on mobile(one plus 3T)

**Comment by ahmeturun** [comment]
I haven't checked out the repo for along time. If have time I'll try to see what's wrong.

**Comment by midhunpmohan** [comment]
could you please check, may be it will help me alot

**Comment by ahmeturun** [comment]
the 'camera' api has been changed to 'camera2' since android version 5.0(see details [here](https://source.android.com/devices/camera/versioning)), and this application is created using old camera api. So I'm afraid but you cannot run it on android version higher than 5.0. If you need to run it on higher android version, you need to change the usage of 'camera' api to 'camera2' on your own fork.
